# Generated by Django 3.0.8 on 2020-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='drugs',
            field=models.ManyToManyField(blank=True, related_name='drugs', to='medbase.Drug', verbose_name='Список лекарств'),
        ),
    ]
