# Generated by Django 3.0.8 on 2020-07-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0003_auto_20200717_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='drugs',
            field=models.ManyToManyField(blank=True, null=True, related_name='drugs', to='medbase.Drug', verbose_name='Список лекарств'),
        ),
    ]
