# Generated by Django 3.0.8 on 2020-07-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0005_auto_20200717_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='desciprion',
            field=models.FloatField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='title',
            field=models.CharField(blank=True, choices=[('Аспирин', 'Аспирин'), ('Витамин С', 'Витамин С'), ('Витамин Б', 'Витамин Б'), ('Парацетамол', 'Парацетамол'), ('Спазмлгон', 'Спазмлгон')], max_length=100, verbose_name='Название лекарства'),
        ),
    ]
