# Generated by Django 3.0.8 on 2020-07-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0009_auto_20200727_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='title',
            field=models.CharField(blank=True, choices=[('Терапевт', 'терапевт'), ('Хирург', 'хирург'), ('Парацетамол', 'Парацетамол')], max_length=100, verbose_name='Название лекарства'),
        ),
    ]
