# Generated by Django 3.0.8 on 2020-07-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0010_auto_20200727_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pill', to='medbase.Pill'),
        ),
    ]
