# Generated by Django 3.0.8 on 2020-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0012_auto_20200727_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='pill',
        ),
        migrations.AlterField(
            model_name='drug',
            name='title',
            field=models.CharField(choices=[('Аспирин', 'Аспирин'), ('Витамин А', 'Витамин А'), ('Витамин Б', 'Витамин Б'), ('Валерьянка', 'Валерьянка'), ('нет назначений', 'нет назначений')], default='нет назначений', max_length=100, verbose_name='Название лекарства'),
        ),
    ]
