# Generated by Django 3.0.8 on 2020-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0014_auto_20200728_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='pill',
        ),
        migrations.AlterField(
            model_name='drug',
            name='title',
            field=models.CharField(choices=[('Винатмин А', 'Винатмин А'), ('Винатмин Б', 'Винатмин Б'), ('Винатмин С', 'Винатмин С'), ('Аспирин', 'Аспирин'), ('Парацетамол', 'Парацетамол')], max_length=100, verbose_name='лекарство'),
        ),
    ]
