# Generated by Django 3.0.8 on 2020-07-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0016_auto_20200730_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='pill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pill', to='medbase.Pill'),
        ),
    ]
