# Generated by Django 3.0.8 on 2020-07-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0022_auto_20200730_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='назначение')),
                ('dose', models.FloatField(null=True, verbose_name='Дозировка в мг.')),
                ('desciprion', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Recepi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appoint', to='medbase.Appointment')),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pill', to='medbase.Pill')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='drugs',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.AddField(
            model_name='patient',
            name='medication',
            field=models.ManyToManyField(blank=True, related_name='medication', to='medbase.Recepi', verbose_name='Список лекарств'),
        ),
    ]
