# Generated by Django 3.0.8 on 2020-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0023_auto_20200731_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medication',
        ),
        migrations.AddField(
            model_name='patient',
            name='recepi',
            field=models.ManyToManyField(blank=True, related_name='recepi', to='medbase.Recepi', verbose_name='Список лекарств'),
        ),
    ]
