# Generated by Django 3.0.8 on 2020-08-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0027_auto_20200802_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepi',
            name='desciprion',
        ),
        migrations.RemoveField(
            model_name='recepi',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='recepi',
            name='title',
        ),
        migrations.AddField(
            model_name='recepi',
            name='appoint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='appoint', to='medbase.Appointment'),
            preserve_default=False,
        ),
    ]
