# Generated by Django 3.0.8 on 2020-08-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0028_auto_20200802_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepi',
            name='desciprion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='recepi',
            name='dose',
            field=models.FloatField(null=True, verbose_name='Дозировка в мг.'),
        ),
        migrations.AddField(
            model_name='recepi',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='назначение'),
        ),
    ]
