# Generated by Django 3.0.8 on 2020-08-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0029_auto_20200802_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepi',
            name='appoint',
        ),
    ]
