# Generated by Django 3.0.8 on 2020-09-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0030_remove_recepi_appoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='сепциализация')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recepi',
        ),
        migrations.AddField(
            model_name='patient',
            name='recepi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='medbase.Recepi', verbose_name='Список лекарств'),
        ),
    ]
