# Generated by Django 3.0.8 on 2020-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0031_auto_20200907_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='recepi',
        ),
        migrations.AddField(
            model_name='patient',
            name='recepi',
            field=models.ManyToManyField(blank=True, null=True, related_name='patient', to='medbase.Recepi', verbose_name='Список лекарств'),
        ),
    ]
