# Generated by Django 3.0.8 on 2020-09-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0032_auto_20200907_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='recepi',
            field=models.ManyToManyField(blank=True, related_name='patient', to='medbase.Recepi', verbose_name='Список лекарств'),
        ),
    ]
