# Generated by Django 3.0.8 on 2020-09-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0033_auto_20200907_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='recepi',
        ),
        migrations.AddField(
            model_name='patient',
            name='recepi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='medbase.Recepi', verbose_name='Список лекарств'),
        ),
    ]
