# Generated by Django 3.0.8 on 2020-09-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0034_auto_20200907_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='recepi',
        ),
        migrations.AddField(
            model_name='recepi',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepi', to='medbase.Patient', verbose_name='имя пацикета'),
        ),
    ]
