# Generated by Django 3.0.8 on 2020-09-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0035_auto_20200907_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepi',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recepi', to='medbase.Patient', verbose_name='пациент'),
        ),
    ]
