# Generated by Django 3.0.8 on 2020-09-10 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medbase', '0036_auto_20200907_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
