# Generated by Django 3.0.8 on 2020-09-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0037_auto_20200910_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spec', to='medbase.Specialization', verbose_name='Специализация'),
        ),
    ]
