# Generated by Django 3.0.8 on 2020-09-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0039_auto_20200919_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specializations',
            new_name='specialization',
        ),
    ]
