# Generated by Django 3.0.8 on 2020-09-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0040_auto_20200919_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Терапевт', 'терапевт'), ('Хирург', 'хирург'), ('Кардиолог', 'Кардиолог')], max_length=100, null=True, verbose_name='Специализация'),
        ),
    ]
